// WorkMirror - High-level analysis engine.
//
// Fetches activity data from the encrypted database, prepares prompts,
// calls the local Ollama instance for AI-generated insights, and returns
// structured DailySummary / WeeklyReport objects.
//
// If the AI is unavailable the analyzer degrades gracefully: the returned
// summaries contain purely statistical data without AI-generated text.

use crate::ai::ollama_client;
use crate::db::{Database, DbError};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::sync::{Arc, Mutex as StdMutex};
use thiserror::Error;

// ---------------------------------------------------------------------------
// Data types
// ---------------------------------------------------------------------------

/// A single day's summary returned to the frontend.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DailySummary {
    pub date: String,
    pub total_active_hours: f64,
    pub deep_work_hours: f64,
    pub top_apps: Vec<(String, f64)>,
    pub insight: String,
    pub suggestion: String,
}

/// A warm, friendly daily note generated by the AI.
///
/// Unlike `DailySummary`, this is meant to be displayed as a personal
/// check-in rather than a performance dashboard.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DailyNote {
    pub date: String,
    pub total_active_hours: f64,
    pub deep_work_hours: f64,
    pub learning_hours: f64,
    pub focus_score: u8,
    pub streak_days: u32,
    pub what_you_did: String,
    pub what_you_learned: String,
    pub good_habit: String,
    pub tip: String,
}

/// A full weekly report containing daily breakdowns and trends.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WeeklyReport {
    pub week_range: String,
    pub daily_summaries: Vec<DailySummary>,
    pub trend_analysis: String,
    pub improvement_suggestions: Vec<String>,
}

// ---------------------------------------------------------------------------
// Error type
// ---------------------------------------------------------------------------

/// Errors from the analysis engine.
#[derive(Debug, Error)]
pub enum AnalysisError {
    #[error("Database error: {0}")]
    Database(#[from] DbError),

    #[error("AI error: {0}")]
    Ai(#[from] ollama_client::AiError),

    #[error("No activity data for the requested period")]
    NoData,
}

// ---------------------------------------------------------------------------
// Analyzer
// ---------------------------------------------------------------------------

/// High-level analysis engine.
///
/// Uses the encrypted database and a local Ollama instance to generate
/// daily summaries and weekly reports.
pub struct Analyzer {
    db: Arc<StdMutex<Database>>,
    ollama_url: Option<String>,
    /// Default model to use for AI generation.
    model: String,
}

impl Analyzer {
    /// Create a new `Analyzer`.
    ///
    /// `ollama_url` defaults to `http://localhost:11434` when `None`.
    pub fn new(db: Arc<StdMutex<Database>>, ollama_url: Option<String>) -> Self {
        Analyzer {
            db,
            ollama_url,
            model: "llama3.2:3b".into(),
        }
    }

    // -----------------------------------------------------------------------
    // Daily summary
    // -----------------------------------------------------------------------

    /// Generate a summary for a single day.
    ///
    /// `date` should be in `YYYY-MM-DD` format.  Returns a `DailySummary`
    /// that always contains statistics; AI insight/suggestion are populated
    /// only when Ollama responds.
    /// Build daily stats and AI prompt (synchronous — no `.await`, so the
    /// `MutexGuard` is dropped before the caller hits any await point).
    fn prepare_daily_summary(
        &self,
        date: &str,
    ) -> Result<(f64, f64, Vec<(String, f64)>, String), AnalysisError> {
        let db = self.db.lock().map_err(|e| {
            AnalysisError::Database(DbError::Sqlite(format!("lock: {e}")))
        })?;

        let activities = db
            .get_activities_by_date(date)
            .map_err(AnalysisError::Database)?;

        if activities.is_empty() {
            return Err(AnalysisError::NoData);
        }

        let mut total_secs: i64 = 0;
        let mut deep_secs: i64 = 0;
        let mut app_times: HashMap<String, i64> = HashMap::new();

        for act in &activities {
            total_secs += act.duration_seconds;
            app_times
                .entry(act.category.clone())
                .and_modify(|t| *t += act.duration_seconds)
                .or_insert(act.duration_seconds);

            let lower = act.window_title.to_lowercase();
            if lower.contains("idea")
                || lower.contains("code")
                || lower.contains("studio")
                || lower.contains("vim")
                || lower.contains("neovim")
                || lower.contains("emacs")
            {
                deep_secs += act.duration_seconds;
            }
        }

        let total_hours = total_secs as f64 / 3600.0;
        let deep_hours = deep_secs as f64 / 3600.0;

        let mut app_list: Vec<(String, i64)> = app_times.into_iter().collect();
        app_list.sort_by(|a, b| b.1.cmp(&a.1));
        let top_apps: Vec<(String, f64)> = app_list
            .into_iter()
            .take(5)
            .map(|(name, secs)| (name, secs as f64 / 3600.0))
            .collect();

        let app_lines: Vec<String> = top_apps
            .iter()
            .map(|(name, hours)| format!("  - {}: {:.1} 小时", name, hours))
            .collect();
        let app_text = app_lines.join("\n");

        let prompt = format!(
            r#"你是一个工作效能分析师。以下是用户{date}的工作数据：
总活跃时间{total_hours:.1}小时，其中深度工作时间{deep_hours:.1}小时。
各应用使用时长如下：
{app_text}

请用一段话总结这一天的工作模式，语气温和但有洞察力，50字以内。"#,
            date = date,
            total_hours = total_hours,
            deep_hours = deep_hours,
            app_text = app_text,
        );

        // `db` (MutexGuard) is dropped here when the function returns.
        Ok((total_hours, deep_hours, top_apps, prompt))
    }

    pub async fn generate_daily_summary(&self, date: &str) -> Result<DailySummary, AnalysisError> {
        let (total_hours, deep_hours, top_apps, prompt) =
            self.prepare_daily_summary(date)?;

        // Try to get AI insight; fall back gracefully.
        let (insight, suggestion) = self.ai_insight(&prompt).await;

        Ok(DailySummary {
            date: date.into(),
            total_active_hours: total_hours,
            deep_work_hours: deep_hours,
            top_apps,
            insight,
            suggestion,
        })
    }

    // -----------------------------------------------------------------------
    // Daily note (warm, personal-style check-in)
    // -----------------------------------------------------------------------

    /// Generate a warm, personal daily note for the given date.
    ///
    /// Includes AI-generated descriptions of what the user did, what they
    /// learned, a positive habit reinforcement, and a gentle tip.  Falls
    /// back to template text if the AI is unavailable.
    ///
    /// `date` should be `YYYY-MM-DD`.  `streak_days` is passed in from the
    /// caller (the `streak` module) so this method stays purely about
    /// analysis.
    pub async fn generate_daily_note(&self, date: &str, streak_days: u32) -> Result<DailyNote, AnalysisError> {
        let (total_hours, deep_hours, top_apps, _) =
            self.prepare_daily_summary(date)?;

        // Learning hours = browser + IDE time (approximation).
        let learning_hours: f64 = top_apps
            .iter()
            .filter(|(name, _)| {
                let l = name.to_lowercase();
                l.contains("browser")
                    || l.contains("chrome")
                    || l.contains("edge")
                    || l.contains("firefox")
                    || l.contains("idea")
                    || l.contains("code")
                    || l.contains("studio")
                    || l.contains("vim")
                    || l.contains("neovim")
            })
            .map(|(_, hrs)| hrs)
            .sum();

        let focus_score = self.compute_focus_score(total_hours, deep_hours);

        // Build the friendly prompt.
        let app_lines: Vec<String> = top_apps
            .iter()
            .map(|(name, hours)| format!("  - {}: {:.1} 小时", name, hours))
            .collect();
        let app_text = app_lines.join("\n");

        let prompt = format!(
            r#"你现在是一个了解用户工作习惯的 AI 助手。以下是用户 {date} 的工作数据：
- 总活跃时间：{total_hours:.1} 小时
- 深度工作时间：{deep_hours:.1} 小时
- 主要使用的应用：{app_text}

请用温暖、鼓励的语气生成以下四句话：
1. "今天你做了什么" — 总结今天的主要活动（20字内）
2. "今天你学到了啥" — 如果有浏览器/IDE相关活动，推测学习了什么（15字内）
3. "做得好的地方" — 一句夸奖（15字内）
4. "一个小建议" — 温和的建议（15字内）

语气像是朋友在跟你聊天，不是老板在评价你。"#,
            date = date,
            total_hours = total_hours,
            deep_hours = deep_hours,
            app_text = app_text,
        );

        // Try AI; fall back to template text on failure.
        let (what_you_did, what_you_learned, good_habit, tip) =
            self.ai_note(&prompt).await;

        Ok(DailyNote {
            date: date.into(),
            total_active_hours: total_hours,
            deep_work_hours: deep_hours,
            learning_hours,
            focus_score,
            streak_days,
            what_you_did,
            what_you_learned,
            good_habit,
            tip,
        })
    }

    // -----------------------------------------------------------------------
    // Weekly report
    // -----------------------------------------------------------------------

    /// Generate a report covering the date range `[start, end]`.
    ///
    /// Both dates should be `YYYY-MM-DD`.
    pub async fn generate_weekly_report(
        &self,
        start: &str,
        end: &str,
    ) -> Result<WeeklyReport, AnalysisError> {
        let mut daily_summaries = Vec::new();

        // Iterate over each day in the range.
        let start_date = chrono::NaiveDate::parse_from_str(start, "%Y-%m-%d")
            .map_err(|e| AnalysisError::Database(DbError::Sqlite(format!("parse date: {e}"))))?;
        let end_date = chrono::NaiveDate::parse_from_str(end, "%Y-%m-%d")
            .map_err(|e| AnalysisError::Database(DbError::Sqlite(format!("parse date: {e}"))))?;

        let mut current = start_date;
        while current <= end_date {
            let date_str = current.format("%Y-%m-%d").to_string();
            match self.generate_daily_summary(&date_str).await {
                Ok(summary) => daily_summaries.push(summary),
                Err(AnalysisError::NoData) => { /* skip days without data */ }
                Err(e) => return Err(e),
            }
            current += chrono::Duration::days(1);
        }

        if daily_summaries.is_empty() {
            return Err(AnalysisError::NoData);
        }

        // Compute weekly aggregates.
        let total_active: f64 = daily_summaries.iter().map(|s| s.total_active_hours).sum();
        let total_deep: f64 = daily_summaries.iter().map(|s| s.deep_work_hours).sum();
        let avg_active = total_active / daily_summaries.len() as f64;

        let trend_prompt = format!(
            r#"你是一个工作效能分析师。用户过去一周（{start} 到 {end}）的工作数据如下：
- 平均每日活跃时间：{avg_active:.1} 小时
- 每周总活跃时间：{total_active:.1} 小时
- 每周深度工作时间：{total_deep:.1} 小时
- 共记录 {days} 个工作日

请分析工作趋势（30字以内），然后给出3条改进建议，每行一条。"#,
            start = start,
            end = end,
            avg_active = avg_active,
            total_active = total_active,
            total_deep = total_deep,
            days = daily_summaries.len(),
        );

        let (trend, suggestions_text) = self.ai_trend(&trend_prompt).await;

        let suggestions: Vec<String> = if suggestions_text.is_empty() {
            Vec::new()
        } else {
            suggestions_text
                .lines()
                .map(|l| l.trim().to_string())
                .filter(|l| !l.is_empty())
                .collect()
        };

        Ok(WeeklyReport {
            week_range: format!("{start} ~ {end}"),
            daily_summaries,
            trend_analysis: trend,
            improvement_suggestions: suggestions,
        })
    }

    // -----------------------------------------------------------------------
    // AI helpers
    // -----------------------------------------------------------------------

    /// Call the AI and return (insight, suggestion).
    /// Falls back to empty strings if the AI is unavailable.
    async fn ai_insight(&self, prompt: &str) -> (String, String) {
        match ollama_client::generate(
            prompt,
            self.ollama_url.as_deref(),
            Some(&self.model),
        )
        .await
        {
            Ok(text) => {
                // Try to split into insight and suggestion.
                let lines: Vec<&str> = text.lines().collect();
                if lines.len() >= 2 {
                    (lines[0].to_string(), lines[1..].join("\n"))
                } else {
                    (text, String::new())
                }
            }
            Err(_) => (String::new(), String::new()),
        }
    }

    /// Call the AI for trend analysis.
    /// Falls back to empty strings.
    async fn ai_trend(&self, prompt: &str) -> (String, String) {
        match ollama_client::generate(
            prompt,
            self.ollama_url.as_deref(),
            Some(&self.model),
        )
        .await
        {
            Ok(text) => {
                let lines: Vec<&str> = text.lines().collect();
                if lines.len() >= 2 {
                    (lines[0].to_string(), lines[1..].join("\n"))
                } else {
                    (text, String::new())
                }
            }
            Err(_) => (String::new(), String::new()),
        }
    }

    // -----------------------------------------------------------------------
    // Daily-note helpers
    // -----------------------------------------------------------------------

    /// Compute a focus score (1–100) from total_active_hours and deep_work_hours.
    fn compute_focus_score(&self, total_hours: f64, deep_hours: f64) -> u8 {
        if total_hours < 0.5 {
            return 10;
        }
        // Ratio of deep vs total, scaled to 0..100.
        let ratio = if total_hours > 0.0 {
            (deep_hours / total_hours).min(1.0)
        } else {
            0.0
        };
        let ratio_score = (ratio * 70.0) as u8;

        // Bonus for total hours: 0..30 points (4h+ gets full bonus).
        let volume_bonus = ((total_hours / 4.0).min(1.0) * 30.0) as u8;

        (ratio_score + volume_bonus).min(100).max(1)
    }

    /// Call the AI for a daily-note style response.
    /// Returns (what_you_did, what_you_learned, good_habit, tip).
    /// Falls back to template text if the AI is unavailable.
    async fn ai_note(&self, prompt: &str) -> (String, String, String, String) {
        match ollama_client::generate(
            prompt,
            self.ollama_url.as_deref(),
            Some(&self.model),
        )
        .await
        {
            Ok(text) => {
                let lines: Vec<&str> = text.lines().collect();
                // Expect up to 4 meaningful lines.
                let line0 = lines
                    .first()
                    .map(|s| s.trim().to_string())
                    .filter(|s| !s.is_empty())
                    .unwrap_or_else(|| self.fallback_what_you_did());
                let line1 = lines
                    .get(1)
                    .map(|s| s.trim().to_string())
                    .filter(|s| !s.is_empty())
                    .unwrap_or_else(|| self.fallback_what_you_learned());
                let line2 = lines
                    .get(2)
                    .map(|s| s.trim().to_string())
                    .filter(|s| !s.is_empty())
                    .unwrap_or_else(|| self.fallback_good_habit());
                let line3 = lines
                    .get(3)
                    .map(|s| s.trim().to_string())
                    .filter(|s| !s.is_empty())
                    .unwrap_or_else(|| self.fallback_tip());
                (line0, line1, line2, line3)
            }
            Err(_) => (
                self.fallback_what_you_did(),
                self.fallback_what_you_learned(),
                self.fallback_good_habit(),
                self.fallback_tip(),
            ),
        }
    }

    // -----------------------------------------------------------------------
    // Fallback templates (when AI is unavailable)
    // -----------------------------------------------------------------------

    fn fallback_what_you_did(&self) -> String {
        "今天也在认真工作呢".into()
    }

    fn fallback_what_you_learned(&self) -> String {
        "保持学习，每天都进步".into()
    }

    fn fallback_good_habit(&self) -> String {
        "坚持记录就是很棒的开始！".into()
    }

    fn fallback_tip(&self) -> String {
        "记得起来走走，活动一下".into()
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::db::Database;
    use std::sync::{Arc, Mutex};

    fn create_test_db() -> (Arc<Mutex<Database>>, crate::db::Activity) {
        let db = Database::open_memory().expect("in-memory db");
        let act = crate::db::Activity {
            id: None,
            timestamp: "2026-05-24T09:00:00".into(),
            window_title: "Visual Studio Code - WorkMirror".into(),
            process_name: "code.exe".into(),
            duration_seconds: 7200, // 2 hours
            category: "dev".into(),
        };
        db.insert_activity(&act).expect("insert");

        let act2 = crate::db::Activity {
            id: None,
            timestamp: "2026-05-24T11:00:00".into(),
            window_title: "Chrome".into(),
            process_name: "chrome.exe".into(),
            duration_seconds: 3600, // 1 hour
            category: "browser".into(),
        };
        db.insert_activity(&act2).expect("insert");

        (Arc::new(Mutex::new(db)), act)
    }

    #[test]
    fn daily_summary_empty_data_returns_error() {
        let db = Database::open_memory().expect("in-memory db");
        let analyzer = Analyzer::new(Arc::new(Mutex::new(db)), None);
        let rt = tokio::runtime::Runtime::new().unwrap();
        let result = rt.block_on(analyzer.generate_daily_summary("2026-05-24"));
        assert!(result.is_err());
        match result {
            Err(AnalysisError::NoData) => {} // expected
            _ => panic!("expected NoData error"),
        }
    }

    #[test]
    fn daily_summary_computes_correct_hours() {
        let (db_arc, _) = create_test_db();
        let analyzer = Analyzer::new(db_arc, None);
        let rt = tokio::runtime::Runtime::new().unwrap();
        let summary = rt
            .block_on(analyzer.generate_daily_summary("2026-05-24"))
            .expect("summary");

        assert_eq!(summary.date, "2026-05-24");
        assert_eq!(summary.total_active_hours, 3.0); // 2h + 1h
        // code.exe counts as deep work -> 2 hours.
        assert!((summary.deep_work_hours - 2.0).abs() < 0.001);
        // AI fields are empty since no Ollama running.
        assert!(summary.insight.is_empty());
        assert!(summary.suggestion.is_empty());
    }

    #[test]
    fn daily_summary_top_apps_ordered() {
        let (db_arc, _) = create_test_db();
        let analyzer = Analyzer::new(db_arc, None);
        let rt = tokio::runtime::Runtime::new().unwrap();
        let summary = rt
            .block_on(analyzer.generate_daily_summary("2026-05-24"))
            .expect("summary");

        // Two apps: dev (2h) and browser (1h)
        assert_eq!(summary.top_apps.len(), 2);
        assert_eq!(summary.top_apps[0].0, "dev");
        assert!((summary.top_apps[0].1 - 2.0).abs() < 0.001);
        assert_eq!(summary.top_apps[1].0, "browser");
        assert!((summary.top_apps[1].1 - 1.0).abs() < 0.001);
    }

    #[test]
    fn prompt_template_contains_key_elements() {
        let prompt = format!(
            r#"你是一个工作效能分析师。以下是用户2026-05-24的工作数据：
总活跃时间3.0小时，其中深度工作时间2.0小时。
各应用使用时长如下：
  - dev: 2.0 小时
  - browser: 1.0 小时

请用一段话总结这一天的工作模式，语气温和但有洞察力，50字以内。"#
        );
        assert!(prompt.contains("工作效能分析师"));
        assert!(prompt.contains("2026-05-24"));
        assert!(prompt.contains("3.0"));
        assert!(prompt.contains("dev"));
        assert!(prompt.contains("browser"));
        assert!(prompt.contains("50字以内"));
    }

    #[test]
    fn weekly_report_empty_range() {
        let db = Database::open_memory().expect("in-memory db");
        let analyzer = Analyzer::new(Arc::new(Mutex::new(db)), None);
        let rt = tokio::runtime::Runtime::new().unwrap();
        let result = rt.block_on(analyzer.generate_weekly_report("2099-01-01", "2099-01-07"));
        assert!(result.is_err());
        match result {
            Err(AnalysisError::NoData) => {} // expected
            _ => panic!("expected NoData error"),
        }
    }

    #[test]
    fn weekly_report_with_data() {
        let (db_arc, _) = create_test_db();
        let analyzer = Analyzer::new(db_arc, None);
        let rt = tokio::runtime::Runtime::new().unwrap();
        let report = rt
            .block_on(analyzer.generate_weekly_report("2026-05-24", "2026-05-24"))
            .expect("report");

        assert_eq!(report.week_range, "2026-05-24 ~ 2026-05-24");
        assert_eq!(report.daily_summaries.len(), 1);
        assert_eq!(report.daily_summaries[0].total_active_hours, 3.0);
    }

    #[test]
    fn analyzer_creation_defaults() {
        let db = Database::open_memory().expect("in-memory db");
        let analyzer = Analyzer::new(Arc::new(Mutex::new(db)), None);
        assert_eq!(analyzer.model, "llama3.2:3b");
        assert!(analyzer.ollama_url.is_none());
    }

    #[test]
    fn analyzer_creation_custom_url() {
        let db = Database::open_memory().expect("in-memory db");
        let analyzer = Analyzer::new(
            Arc::new(Mutex::new(db)),
            Some("http://192.168.1.100:11434".into()),
        );
        assert_eq!(
            analyzer.ollama_url,
            Some("http://192.168.1.100:11434".into())
        );
    }
}
